config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'

  root :to => redirect('/accesorios')
  resources :accesorios

  resources :ideas

end

app/models/accesorio.rb
class Accesorio < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/accesorios_controller.rb
class AccesoriosController < ApplicationController
  before_action :set_accesorio, only: [:show, :edit, :update, :destroy]

  # GET /accesorios
  # GET /accesorios.json
  def index
    @accesorios = Accesorio.all
  end

  # GET /accesorios/1
  # GET /accesorios/1.json
  def show
  end

  # GET /accesorios/new
  def new
    @accesorio = Accesorio.new
  end

  # GET /accesorios/1/edit
  def edit
  end

  # POST /accesorios
  # POST /accesorios.json
  def create
    @accesorio = Accesorio.new(accesorio_params)

    respond_to do |format|
      if @accesorio.save
        format.html { redirect_to @accesorio, notice: 'Accesorio was successfully created.' }
        format.json { render :show, status: :created, location: @accesorio }
      else
        format.html { render :new }
        format.json { render json: @accesorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accesorios/1
  # PATCH/PUT /accesorios/1.json
  def update
    respond_to do |format|
      if @accesorio.update(accesorio_params)
        format.html { redirect_to @accesorio, notice: 'Accesorio was successfully updated.' }
        format.json { render :show, status: :ok, location: @accesorio }
      else
        format.html { render :edit }
        format.json { render json: @accesorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accesorios/1
  # DELETE /accesorios/1.json
  def destroy
    @accesorio.destroy
    respond_to do |format|
      format.html { redirect_to accesorios_url, notice: 'Accesorio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accesorio
      @accesorio = Accesorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accesorio_params
      params.require(:accesorio).permit(:name, :description, :picture, :cost, :availability)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/accesorios_helper.rb
module AccesoriosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/accesorios/_form.html.erb
<%= form_for(@accesorio) do |f| %>
  <% if @accesorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accesorio.errors.count, "error") %> prohibited this accesorio from being saved:</h2>

      <ul>
      <% @accesorio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <strong>Nombre</strong><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <strong>Descripcion</strong><br>
    <%= f.text_area :description %><br>
  </div>
  <div class="field">
    <strong>Picture</strong><br>
    <%= f.file_field :picture %><br>
  </div>
  <div class="field">
    <strong>Costo</strong><br>
    <%= f.text_field :cost %><br>
  </div>
  <div class="field">
    <strong>Disponibilidad</strong><br>
    <%= f.text_field :availability %><br>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accesorios/edit.html.erb
<h1>Editing accesorio</h1>

<%= render 'form' %>

<%= link_to 'Show', @accesorio %> |
<%= link_to 'Back', accesorios_path %>

app/views/accesorios/index.html.erb
<h1>Listar Mis Accesorios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Imagen</th>
      <th>Costo</th>
      <th>Disponibilidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accesorios.each do |accesorio| %>
      <tr>
        <td><%= accesorio.name %></td>
        <td><%= accesorio.description %></td>
        <td><%= accesorio.picture %></td>
        <td><%= accesorio.cost %></td>
        <td><%= accesorio.availability %></td>
        <td><%= link_to 'Show', accesorio %></td>
        <td><%= link_to 'Edit', edit_accesorio_path(accesorio) %></td>
        <td><%= link_to 'Destroy', accesorio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accesorio', new_accesorio_path %>

app/views/accesorios/new.html.erb
<h1>Nuevo Accesorio</h1>

<%= render 'form' %>

<%= link_to 'Back', accesorios_path %>

app/views/accesorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @accesorio.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @accesorio.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@accesorio.picture_url, :width => 600) if @accesorio.picture.present? %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @accesorio.cost %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @accesorio.availability %>
</p>

<%= link_to 'Edit', edit_accesorio_path(@accesorio) %> |
<%= link_to 'Back', accesorios_path %>

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/new.html.erb
<h1>New idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @idea.picture %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsgirls</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :default, 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">The Accesories App </a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= 'active' if current_page?(accesorios_path) %>">
          <%= link_to 'Accesorios', accesorios_path %>
        </li>
        <li class="<%= 'active' if current_page?(pages_info_path) %>">
          <%= link_to 'Quienes Somos?', pages_info_path %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <%= yield %>
</div>
<footer>
  <div class="container">
    Rails Girls 2016
  </div>
</footer>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/info.html.erb
<h1>Quiénes Somos</h1>
<br><br>
HARAM pajaritas es una propuesta de accesorios masculinos entre los que hay pajaritas (corbatines), pañuelos de solapa, corbatas y uno que otro detalle. <br><br>
HARAM pajaritas es una propuesta responsable con el ambiente porque utiliza retazos de tela de talleres de confección y de fábricas medianas y grandes. HARAM pajaritas toma los retazos, los trata para que puedan ser reutilizados y les da una nueva vida. Alguno conocen esto como [upcycling].<br><br>
HARAM pajaritas es posible gracias a un grupo de mujeres de distintos estratos económicos y sociales de la ciudad de Quito que buscan empoderarse a través del trabajo asociativo, inclusivo, tolerante y no discriminatorio.<br><br>
Cuando compras un accesorio de HARAM pajaritas contribuyes a la reducción de miles de toneladas de textiles desechados cada año por la industria indumentaria y que tardan miles de años en descomponerse.<br><br>


<%= image_tag "ProduccionTelaTanzania.JPG" %>